### ISSUE TITLE
Zooming on mobile is sometimes janky

### ISSUE THREAD

**Issue by scottyantipa** [transcriptic/react-map-interaction#12]
To repro: Open the example app on a mobile device and try pinch zooming. You will notice that frequently the zoom effect is shaky/janky. This seems to be correlated to the speed at which you zoom and also the initial zoom level.

**Comment by Seb-AS** [comment]
hi, any fix for this bug? I found the same issue, try a few ways to fix it but no luck.., sometimes works fluid others jumping.
thanks

**Comment by scottyantipa** [comment]
I haven't found a fix, but also haven't dug in deeply yet. The code for determining which pointer events to use might be the issue. It assumes that the first two events are the first two touch downs. Maybe there is an issue with assuming that the order in the event array is maintained between each change in the position. Not sure.

**Comment by Seb-AS** [comment]
thanks

**Comment by scottyantipa** [comment]
I identified two separate issues:
- I have a fix for this one coming -- The scale is not properly being changed during a pinch/zoom. Specifically, the computed change is too large which means as you zoom in, the points beneath your fingers will zoom together too quickly (and when zooming out, they zoom away too quickly).
- Haven't yet fixed this -- we see a jerky zoom if you pinch up and down vertically for some reason. Sometimes the zoom will even invert such that pinching inwards will cause the scale to increase, not decrease

I may make two separate tasks for these.
