### ISSUE TITLE
Event override on devices supporting multiple interaction methods

### ISSUE THREAD

**Issue by Demango** [transcriptic/react-map-interaction#14]
Currently, on devices that support both touch and mouse, drag to pan [mouse] does not work as it seems to be overridden by hold to pan [touch].
Zoom however appears to function fine with both input methods.

**Comment by scottyantipa** [comment]
You are correct, thanks for the issue. Looks like it only attaches event handlers for touch or mouse, but never both. We should attach both if we detect that the device has the capability. Happy to look at a PR if you have the time. 

Do you have an example of your use case you could post?
