### ISSUE TITLE
On Chrome 56 e.preventDefault doesn't work properly

### ISSUE THREAD

**Issue by scottyantipa** [transcriptic/react-map-interaction#23]
In our onWheel handler we preventDefault so that the browser does not try to scroll the node containing the pinch/zoom element. However in recent versions of chrome they introduced a `passive` option to the event handler which is true by default. See the blog post below. Instead, we should be using the css property `touch-action` (I believe setting `touch-action: none` on the containerNode should do it).

This causes the bad bug of the container node trying to scroll vertically while the user pinch/zooms.

https://developers.google.com/web/updates/2017/01/scrolling-intervention

![Screen Shot 2019-04-17 at 7 56 26 AM](https://user-images.githubusercontent.com/3643611/56310018-79940880-60e6-11e9-982f-92cd54f24ac1.png)
Above you can see the js warning from us calling preventDefault inside a non-passive event handler.

**Comment by tchau** [comment]
+1 thank you for fixing this @scottyantipa , my application recently started being all wonky because of this issue in Chrome 56
