### ISSUE TITLE
Add feature for disabling panning and zooming

### ISSUE THREAD

**Issue by scottyantipa** [transcriptic/react-map-interaction#7]

**Comment by mihaiserban** [comment]
I also subscribe to this.
An option to stop panning and zooming would be very nice. And make sure to allow events to pass throught to other components.

**Comment by scottyantipa** [comment]
Great, thank you @mihaiserban for the PR. 

Could I ask how you are using the component? It is always helpful to see examples so we can get a better idea of what features to prioritize. A screen shot or just a description would be awesome. Thanks!

**Comment by mihaiserban** [comment]
I've used react-map-interaction to add zooming and dragging to a html5 canvas (KonvaJS).
I needed when an element was selected on the canvas to disable the zoom/drag on react-map-interaction for a quick demo.
In the end I'll use KonvaJS own scaling properties and translate the elements on drag/scroll.

**Comment by NataliBILAN** [comment]
Hey! I also need prop  to disable dragging.
I  use 'react-map-interaction' in my slider, this lib is the best for touch devices and also works with a mouse or trackpad (what I need).
When I use a default value (transform: none) to controll the 'translation' zoom doesn't work. Or when I  limit translation by translationBounds={({ xMax: 0, yMax: 0, xMin: 0, yMin: 0 })}
 dragging is disable, but zoom has only one direction  -  to left top :(

**Comment by scottyantipa** [comment]
@NataliBILAN Could you describe a bit more how you are using this, maybe with a screenshot? I'm having trouble understanding how you use this for a slider.

I'm working now on props for disabling panning/zooming. However I'm still considering how the UX should work for the case of disabling translation, but not disabling zooming. You can get into a weird position where you have zoomed in and out several times such that the content has gone off screen (or out of your container) but then cannot drag it back in because you've disabled translation. I'm looking for inspiration from around the web but I haven't really found anything.

Some possibilities:
- Ignore the issue above, and just add disableTranslation and disableZoom props
-  Add the props, but handle the case above by letting the user translation only when the zoom is at a scale other than 1 (e.g. when they are zoomed in or out, they can translate the content)
- Add the props, but when disableTranslation is true, force the translation to be (0, 0) whenever the scale is 1. This will solve the issue that the user may accidentally zoom the content off screen, however it does cause a slightly janky interaction -- the point beneath your cursor will now longer stay beneath the cursor as you zoom (because we force the translation to coincide with (0, 0)).

**Comment by scottyantipa** [comment]
@NataliBILAN Could you checkout PR #11 and test that out locally to see if it fits your use case?
